version: '3.8'

services:
  letrent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: letrent
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.letrent.rule=Host(`let.rafaelcardoso.co.uk`)"
      - "traefik.http.routers.letrent.entrypoints=https"
      - "traefik.http.routers.letrent.tls.certresolver=cloudflare"
      - "traefik.http.services.letrent.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
